spring.application.name=auth-service
spring.profiles.active=local

management.endpoints.web.exposure.include=health,info

logging.level.root=INFO
logging.level.com.kubemanager=DEBUG

security.jwt.secret=ThisIsMyVeryLongSecretKeyForKubeManagerPlatformAuthentication123456789
security.jwt.access-token-expiration=900
security.jwt.refresh-token-expiration=604800



spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}

spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}

spring.security.oauth2.client.registration.github.scope=read:user,user:email