
spring.application.name=auth-service
spring.profiles.active=local

management.endpoints.web.exposure.include=health,info

security.jwt.refresh-token-expiration=604800

logging.level.root=INFO
logging.level.com.kubemanager=DEBUG