spring.application.name=ai-service

server.port=8086



kubemanager.services.cluster-service.url=http://localhost:8084
management.endpoints.web.exposure.include=health,info,metrics

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0.3