spring.application.name=ai-service

server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5432/kubemanager_ai
spring.datasource.username=postgres
spring.datasource.password=yash8252
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false


kubemanager.services.cluster-service.url=http://localhost:8084
management.endpoints.web.exposure.include=health,info,metrics

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0.3