spring:
  application:
    name: api-gateway

  profiles:
    active: local

server:
  port: 8081


security:
  jwt:
    secret: ThisIsMyVeryLongSecretKeyForDistributedUrlShortenerApplication123456789

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO